# .github/workflows/daily-run.yml

name: Daily run

on:
  schedule:
    - cron: "0 18 * * *"
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"
          cache: "pip"
          cache-dependency-path: "scheduler/pyproject.toml"

      - name: Install package
        working-directory: ./scheduler
        run: pip install -e "."

      - name: Run plantiq
        working-directory: ./scheduler
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          OPENWEATHERMAP_API_KEY: ${{ secrets.OPENWEATHERMAP_API_KEY }}
          NTFY_TOPIC: ${{ secrets.NTFY_TOPIC }}
        run: python -m plantiq.run
